### ISSUE TITLE
Missing abilities/spells?

### ISSUE THREAD

**Issue by Doxmia** [nonowazu/vue-xivtooltips#61]
Not really sure if this would need to be updated for Endwalker but certain spells or abilities just don't seem to work. Like Soteria for Sage as an example even though Kerachole does? Since it uses XIVAPI I was under the impression that it would "just work" but certain abilities are just not showing for me.

**Comment by Doxmia** [comment]
Just as a visual example: [https://imgur.com/U1OHWlI](https://imgur.com/U1OHWlI)

That's the name/action ID I am using - I see data show up properly directly at xivapi (both under the search as well as the action/24318 directly). 

Kind of puzzled here.

**Comment by Doxmia** [comment]
Pretty sure it's something on my end since no new tooltips (even for older abilities) are loading so it's almost like they were working fine and then cached but now refuse to update anything new. Seeing this warning when I try to pull abilities I haven't recently: `Cross-Origin Read Blocking (CORB) blocked cross-origin response https://xivapi.com/ with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

Not sure what I changed or where but I guess I'll keep poking around.

**Comment by Doxmia** [comment]
Well I'm not making any progress on this. I tested off server locally and can get all tooltips to work properly but I am seeing this error on a hosted site which I'm not sure if that would cause the problem or not:

`Uncaught (in promise) TypeError: Cannot create property 'cacheTime' on boolean 'false'
    at actions.js:64:27
    at Array.reduce (<anonymous>)
    at actions.js:63:55
    at actions.js:40:21`

Any ideas would be great! Maybe I just need to sleep on it.

**Comment by Doxmia** [comment]
Clearing local storage fixed it, still uncertain what caused it in the first place.

**Comment by SaltedLevity** [comment]
Glad you were able to get it working either way! 😃
